---
layout: ../../../layouts/Dropdowns.astro
title: "Cursus"
childs:
  - title: "Association du cursus SPRINT (Sorbonne Physique Intensif et Nouvelles Technologies)"
    href: "/associations/cursus/sprint"
  - title: "Association du Cursus Master en Ingénierie (CMI)"
    href: "/associations/cursus/cmi"
  - title: "Association du Master d'Ingénierie (AMI)"
    href: "/associations/cursus/ami"
  - title: "Association Étudiante du master de Biologie Intégrative et Physiologie  (AEBIP)"
    href: "/associations/cursus/aebip"
  - title: "Association du master de Biologie Moléculaire et Cellulaire (AvéBMC)"
    href: "/associations/cursus/avebmc"
  - title: "Association du master de Biodiversité, Écologie et Évolution (GoBEE)"
    href: "/associations/cursus/gobee"
  - title: "Assciation du master Sol, Eau et Environnement (I'SEE)"
    href: "/associations/cursus/isee"
  - title: "Association de cursus en Sciences, Gestion et Management de l’Innovation (SGMI)"
    href: "/associations/cursus/sgmi"
  - title: "Association Bicursiosité des doubles cursus Sciences + Histoire/Philo/Musico/ETC"
    href: "/associations/cursus/bicursiosite"
  - title: "Double Licence Sciences et Droit - Sorbonne Université / Panthéon Assas"
    href: "/associations/cursus/scdr"
---
