---
layout: ../../../layouts/Dropdowns.astro
title: "Ludique & Artistique"
childs:
  - title: "JEUX : Play Sorbonne Université"
    href: "/associations/ludi_art/psu"
  - title: "ÉCHECS : Les Fous Des Tours (LFDT)"
    href: "/associations/ludi_art/lfdt"
  - title: "JEU DE RÔLE : Dés'N'Dés"
    href: "/associations/ludi_art/desndes"
  - title: "JEUX VIDÉOS : SU Esport"
    href: "/associations/ludi_art/suesport"
  - title: "FILM : Super 8 "
    href: "/associations/ludi_art/super8"
  - title: "MÉDIAS & AUDIOVISUEL : TV JUSSIEU"
    href: "/associations/ludi_art/tvjussieu"
  - title: "VULGARISATION : Je Science donc Je Suis (JS²) "
    href: "/associations/ludi_art/js2"
  - title: "JOURNAL : Alma Mater"
    href: "/associations/ludi_art/alamamater"
  - title: "MUSIQUE : Jam Jussieu"
    href: "/associations/ludi_art/jam"
  - title: "FANFARE : Moktar Sound System"
    href: "/associations/ludi_art/moktar"
  - title: "PHOTOGRAPHIE : Lux Fabrica"
    href: "/associations/ludi_art/luxfabrica"
  - title: "SPORT : ASsociation Sportive Universitaire de la faculté des Sciences et Ingénierie et de la faculté de Médecine (ASSU SIM)"
    href: "/associations/ludi_art/assusim"
---
