---
layout: ../../../layouts/Dropdowns.astro
title: "Polytech"
childs:
  - title: "BDE Polytech"
    href: "/associations/polytech/bde"
  - title: "POLYPEIP, club du BDE Polytech pour la filière PEIP"
    href: "/associations/polytech/polyip"
  - title: "ART & CULTURE : Bureau Des Arts et de la Culture (BDAC)"
    href: "/associations/polytech/bdac"
  - title: "ÉTUDIANTS INTERNATIONAUX : Polytech Without Borders (PWB), club du BDE Polytech "
    href: "/associations/polytech/pwb"
  - title: "SPORT : Bureau des Sports (BDS), club du BDE Polytech"
    href: "/associations/polytech/bds"
  - title: "CARITATIF : Polycoeur , club du BDE Polytech"
    href: "/associations/polytech/polycoeur"
  - title: "VULGARISATION : Vert La Science , club du BDE Polytech"
    href: "/associations/polytech/vls"
  - title: "JEUX & INFORMATIQUE : Club d'Informatique et d'Agrement (CIA)"
    href: "/associations/polytech/cia"
  - title: "ROBOTIQUE : Robotech"
    href: "/associations/polytech/robotech"
  - title: "ECOLOGIE : InTerreAgir"
    href: "/associations/polytech/interreagir"
  - title: "MUSIQUE : InVivo"
    href: "/associations/polytech/invivo"
  - title: "ENTREPRENARIAT : Enactus"
    href: "/associations/polytech/enactus"
  - title: "FEMINISME : HeForShe"
    href: "/associations/polytech/heforshe"
---
Mail général des associations de Polytech Sorbonne : associations.polytechsorbonne@gmail.com